name: Deploy Flutter Web to GitHub Pages Test1

on:
  push:
    branches:
      - rich-text-implementation  # મહત્વનો ફેરફાર: અહીં તમારી બ્રાન્ચનું નામ લખ્યું છે

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web App
        # અહીં તમારા રીપોઝીટરીનું નામ 'editor_app' છે, તેથી base-href બરાબર છે.
        run: flutter build web --release --base-href "/editor_app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
