name: Deploy Flutter Web to GitHub Pages

on:
  # જ્યારે તમે કોડ પુશ કરો ત્યારે રન થશે
  push:
    branches:
      - rich-text-implementation
  
  # મેન્યુઅલી રન કરવા માટે બટન
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # અહીં વર્ઝન બદલીને નવું કર્યું છે જે તમારા પ્રોજેક્ટ સાથે સુસંગત છે
          flutter-version: '3.24.3'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web App
        # base-href માં તમારા રીપોઝીટરીનું નામ editor_app છે
        run: flutter build web --release --base-href "/editor_app/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
